### PR TITLE
Feature slurm testing

### PR DESCRIPTION
**Pull request by Ahad-Allen**
This PR is intended to add functionality to allow a script to run on the cluster and generate an nwb file for an ephys input. Though the slurm related changes are final, the ephys trial information changes are not, so I am merging the changes into the ephys_write_stim branch rather than main.

### CODE REVIEW

**Comment by jeromelecoq** [comment]
Ok. Can you make your conda environment outside of your home directory?

**Comment by jeromelecoq** [comment]
Does this conversion really required 15 cores and only 8GB of memory?

**Comment by jeromelecoq** [comment]
Have you tested it ?

**Comment by Ahad-Allen** [comment]
> Does this conversion really required 15 cores and only 8GB of memory?

I will check the core usage to confirm, but 8gb was sufficient. The default value was too low and resulted in memory error, but 8gb was able to run conversions with no issues.

**Comment by Ahad-Allen** [comment]
> Ok. Can you make your conda environment outside of your home directory?

No problem, I'll get this done 👍

**Review by jeromelecoq — APPROVED** [review]
Looks good

**Pull request merged**
