### PR TITLE
Adding Sync Utils to Cron for Dandi 

### PR DESCRIPTION
**Pull request by Ahad-Allen**
# Overview:

If a session is deleted from or re-uploaded to dandi, it will cause our firebase to no longer show the correct path for its location on dandi. We want to adjust the cron such that it checks the current dandi path of each session:
Tracks: https://github.com/orgs/AllenInstitute/projects/17/views/1?pane=issue&itemId=30932961

# Code Changes:

I've added a dandi_functions.py file in utils which checks all file assets on dandi for each project. It then updates the firebase to store each of these paths. These functions are called by the cron and should update the database ever hour.

# Use Changes:

This should not change how the repo is used.

# Testing:

This has been used for the past 2 weeks and seems to be accurately reflecting changes done with uploads and deletes. Once one of the embargoed datasets is finalized, we may want to add a unit test which checks ALL paths on firebase for that project. 

# Notes:

We have a PR template and guidelines now!

### CODE REVIEW

**Comment by Ahad-Allen** [comment]
Feel free to ignore the last 14 commits, they are just related to flake8

**Comment by jeromelecoq** [comment]
This PR is very large. Please do not do that again.

**Comment by jeromelecoq** [comment]
It also seem to contain a lot of changes that not related to the description. So it is hard to read

**Comment by jeromelecoq** [comment]
the syncing code seems correct. But I am having trouble evaluating the re-org. I suggest we merge and go over the repo together.

**Pull request merged**
